name: Publish to Npm
on:
  push:
    branches: [ main ]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm ci
          npm run buildT
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_DEPLOY }}